from __future__ import annotations

import argparse
import json
import sqlite3
from pathlib import Path

from sqlalchemy import text

from packages.infrastructure.db.session import engine

DDL = """
CREATE TABLE IF NOT EXISTS tenants (
  id TEXT PRIMARY KEY, slug VARCHAR(100) NOT NULL UNIQUE, name VARCHAR(200) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active', plan VARCHAR(64) NOT NULL DEFAULT 'standard',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS users_v2 (
  id TEXT PRIMARY KEY, oidc_subject VARCHAR(255) NOT NULL UNIQUE, email VARCHAR(320) NOT NULL DEFAULT '',
  display_name VARCHAR(200) NOT NULL DEFAULT '', status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS tenant_memberships (
  id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  user_id TEXT NOT NULL REFERENCES users_v2(id) ON DELETE CASCADE, role VARCHAR(64) NOT NULL DEFAULT 'viewer',
  status VARCHAR(32) NOT NULL DEFAULT 'active', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id, user_id)
);
CREATE TABLE IF NOT EXISTS roles (id TEXT PRIMARY KEY, name VARCHAR(64) NOT NULL UNIQUE, scope VARCHAR(32) NOT NULL DEFAULT 'tenant');
CREATE TABLE IF NOT EXISTS permissions (id TEXT PRIMARY KEY, name VARCHAR(128) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS role_permissions (role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE, permission_id TEXT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE, PRIMARY KEY(role_id, permission_id));
CREATE TABLE IF NOT EXISTS refresh_tokens (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users_v2(id) ON DELETE CASCADE, token_hash VARCHAR(128) NOT NULL UNIQUE, device_name VARCHAR(200) NOT NULL DEFAULT '', expires_at TIMESTAMP NOT NULL, revoked_at TIMESTAMP, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS msm_servers (
  id INTEGER PRIMARY KEY AUTOINCREMENT, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  name VARCHAR(200) NOT NULL, address TEXT NOT NULL, token TEXT NOT NULL, enabled BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id, name)
);
CREATE TABLE IF NOT EXISTS msm_jobs (
  id TEXT PRIMARY KEY, tenant_id TEXT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  type VARCHAR(100) NOT NULL, server_id INTEGER REFERENCES msm_servers(id) ON DELETE SET NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'queued', payload TEXT NOT NULL DEFAULT '{}', error TEXT NOT NULL DEFAULT '',
  idempotency_key VARCHAR(255), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(tenant_id, idempotency_key)
);
CREATE INDEX IF NOT EXISTS ix_msm_jobs_tenant_status ON msm_jobs(tenant_id, status, created_at);
"""


def initialize() -> None:
    ddl = DDL
    if engine.dialect.name == "postgresql":
        ddl = ddl.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
    with engine.begin() as connection:
        for statement in ddl.split(";\n"):
            if statement.strip():
                connection.execute(text(statement))


def import_sqlite(path: Path, slug: str, name: str) -> dict[str, int | str]:
    initialize()
    source = sqlite3.connect(path)
    source.row_factory = sqlite3.Row
    with engine.begin() as target:
        tenant_id = target.execute(text("SELECT id FROM tenants WHERE slug=:slug"), {"slug": slug}).scalar()
        if not tenant_id:
            import uuid
            tenant_id = str(uuid.uuid4())
            target.execute(text("INSERT INTO tenants (id, slug, name) VALUES (:id, :slug, :name)"), {"id": tenant_id, "slug": slug, "name": name})
    server_count = 0
    if "servers" in {row[0] for row in source.execute("SELECT name FROM sqlite_master WHERE type='table'")}: 
        for row in source.execute("SELECT name, address, token, enabled FROM servers"):
            with engine.begin() as target:
                target.execute(text("INSERT INTO msm_servers (tenant_id, name, address, token, enabled) VALUES (:tenant_id, :name, :address, :token, :enabled) ON CONFLICT DO NOTHING"), {"tenant_id": tenant_id, **dict(row)})
            server_count += 1
    source.close()
    return {"tenant_id": tenant_id, "servers": server_count}


def main() -> None:
    parser = argparse.ArgumentParser(description="Initialize PostgreSQL schema or import a legacy SQLite database")
    parser.add_argument("--init", action="store_true")
    parser.add_argument("--sqlite", type=Path)
    parser.add_argument("--tenant-slug", default="default")
    parser.add_argument("--tenant-name", default="Default Tenant")
    args = parser.parse_args()
    if args.init:
        initialize()
        print(json.dumps({"initialized": True}))
    elif args.sqlite:
        print(json.dumps(import_sqlite(args.sqlite, args.tenant_slug, args.tenant_name)))
    else:
        parser.error("choose --init or --sqlite")


if __name__ == "__main__":
    main()
